spring.application.name=music-service
server.port=8082
#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/music_db
spring.datasource.username=postgres
spring.datasource.password=postgres
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Logs
logging.level.root=INFO
logging.level.musicplateform=DEBUG
#Kafka(Producer)
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
# File Storage
file.upload.dir=uploads
# File upload size
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB