spring.application.name=playlist-service
server.port=8083
#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/playlist_db
spring.datasource.username=postgres
spring.datasource.password=postgres
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Logs
logging.level.root=INFO
logging.level.com.musicplatform.playlistservice=DEBUG
#Kafka (Consumer)
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=playlist-service-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#Other Services
music-service.url=http://localhost:8082